#!/bin/sh -
# shell-script to automate the (re)factorization of reference numbers
# Usage: factor_from_rels name <parameters>

# update if necessary, or better autoselect directory from site (LORIA/LIX)
d=/net/tiramisu/cado1/cado/Examples
tmp=/localdisk/tmp
# $cado should point to the ../dist/src directory
cado="`dirname $0`"

name=$1

# default parameters
prune=1.0; maxlevel=6; cwmax=10; rwmax=100

if [ $# -ge 2 ]; then prune=$2; fi
if [ $# -ge 3 ]; then maxlevel=$3; fi
if [ $# -ge 4 ]; then cwmax=$4; fi
if [ $# -ge 5 ]; then rwmax=$5; fi

# number of processors
mt=2

/bin/rm -fr $tmp/$name
tmp=$tmp/$name
mkdir $tmp

cp $d/$name/$name.poly $tmp
$cado/sieve/makefb -poly $tmp/$name.poly > $tmp/$name.roots
$cado/postsieve/checknorms/checknorms -poly $tmp/$name.poly $d/$name/$name.rels >> $tmp/rels.0
$cado/linalg/freerel -poly $tmp/$name.poly $tmp/rels.0 > $tmp/rels.free
echo "cado=$cado" > $tmp/params
echo "root=$tmp/$name" >> $tmp/params
echo "prune=$prune" >> $tmp/params
echo "maxlevel=$maxlevel" >> $tmp/params
echo "cwmax=$cwmax" >> $tmp/params
echo "rwmax=$rwmax" >> $tmp/params
echo "mt=$mt" >> $tmp/params
echo "bwstrat=0" >> $tmp/params
echo "keep_purge=400000" >> $tmp/params
echo "ratio=1.5" >> $tmp/params
$cado/merge_linalg_sqrt2.sh $tmp/params
/bin/rm -fr $tmp/$name

