#!/bin/csh
# script to run the polynomial selection on several machines
# Usage: doit cxxx.n machines effort
#        cxxx.n   composite file (one line with n:...)
#        machines program giving list of machines to use (one per line,
#                 with n times the machine name if it has n cores)
#        effort   -e parameter for polyselect
#
# Assumes the CADO environment variable is set, so that
# $CADO/polyselect/polyselect is the polynomial selection program

set DIR=`dirname $1`
set COMP=`basename $1 .n`
set B='$1'

set doit=$DIR/doit$$
echo "exec $CADO/polyselect/polyselect -b $B -e $3 < $1 >& $DIR/$COMP.poly.$B &" > $doit
chmod u+x $doit

set machines=`$2`
@ start = 1
foreach m ($machines)
   echo Starting polyselect on $m with b=$start
   ssh $m "nice +20 $doit $start"
   @ start = $start + 1
end

# /bin/rm $doit
