#!/bin/sh

# This script gives a human-parsable (and ctags-friendly) version of the
# prototypes generated by the cpp craziness in fppol_*.h

echo -e "#include \"fppol.h\"\n#include \"types.h\"" | gcc -DUSE_F2 -CC -E -xc - | perl -e 'my $keep = true; my $weed=0; while (<STDIN>) { my $line = $_; if (m,^# \d+ "(.*),) { my $file=$1; if ($file =~ m,^/,) { print "#include \"$file\"\n"; $weed=1; } else { $weed=0; } } print unless $weed; }' | indent
