#!/bin/csh
setenv NOMAD_MAX_BB_EVAL 100
# the number of threads should not be too large for small numbers, see #21417
setenv NUM_THREADS 2
foreach f (c60 c65 c70 c75 c80 c85)
   echo "Optimizing parameters for ${f}:"
   cp ../../parameters/factor/params.$f .
   cp ../../parameters/polynomials/$f.poly .
   ./optimize.sh params.$f $f.poly >& /dev/null
   diff params.$f params.$f.opt
   cp params.$f.opt ../../parameters/factor/params.$f
end
setenv NUM_THREADS 4
foreach f (c90 c95 c100 c105 c110 c115)
   echo "Optimizing parameters for ${f}:"
   cp ../../parameters/factor/params.$f .
   cp ../../parameters/polynomials/$f.poly .
   ./optimize.sh params.$f $f.poly >& /dev/null
   diff params.$f params.$f.opt
   cp params.$f.opt ../../parameters/factor/params.$f
end
setenv NUM_THREADS 8
foreach f (c120 c125 c130 c135 c140 c145)
   echo "Optimizing parameters for ${f}:"
   cp ../../parameters/factor/params.$f .
   cp ../../parameters/polynomials/$f.poly .
   ./optimize.sh params.$f $f.poly >& /dev/null
   diff params.$f params.$f.opt
   cp params.$f.opt ../../parameters/factor/params.$f
end
setenv NUM_THREADS 16
foreach f (c150 c155 c160 c165 c170 c175)
   echo "Optimizing parameters for ${f}:"
   cp ../../parameters/factor/params.$f .
   cp ../../parameters/polynomials/$f.poly .
   ./optimize.sh params.$f $f.poly >& /dev/null
   diff params.$f params.$f.opt
   cp params.$f.opt ../../parameters/factor/params.$f
end
