message(STATUS "Checking for alloca.h")
find_path   (ALLOCA_INCDIR alloca.h DOC "alloca.h")
string(COMPARE NOTEQUAL "${ALLOCA_INCDIR}" ALLOCA_INCDIR-NOTFOUND HAVE_ALLOCA_H)
if (HAVE_ALLOCA_H)
Message(STATUS "Checking for alloca.h -- found in ${ALLOCA_INCDIR}")
else (HAVE_ALLOCA_H)
message(STATUS "Checking for alloca.h -- not found")
endif (HAVE_ALLOCA_H)
