macro(string_join var delimiter str_list)
    set(_ret "")
    foreach(_str ${str_list})
        if(_ret STREQUAL "")
            set(_ret "${_str}")
        else(_ret STREQUAL "")
            set(_ret "${_ret}${delimiter}${_str}")
        endif(_ret STREQUAL "")
    endforeach(_str ${str_list})
    foreach(_str ${ARGN})
        if(_ret STREQUAL "")
            set(_ret "${_str}")
        else(_ret STREQUAL "")
            set(_ret "${_ret}${delimiter}${_str}")
        endif(_ret STREQUAL "")
    endforeach(_str ${ARGN})
    set(${var} "${_ret}")
endmacro(string_join var delimiter str_list)


