#!/bin/csh
set in=$1
set d=$2

/bin/rm -f $d/cpu $d/rep $d/mem

foreach f ($in/201*)
   set t1=`grep "Total cpu time" $f | cut -d" " -f5 | sed 's/s//g'`
   set t2=`grep "Total cpu time" $f | cut -d" " -f9`
   set t3=`grep "Total cpu time" $f | cut -d" " -f16`
   echo $t1 $t2 $t3 >> $d/cpu
   grep Total $f | grep reports | cut -d" " -f3 | sed 's/s//g' >> $d/rep
   grep PeakMemusage $f | cut -d" " -f5 | sed 's/s//g' >> $d/mem
end

gnuplot << EOF
set terminal gif
set output '$d/cpu.gif'
set yrange [0:]
plot "$d/cpu" using 1 title "total time (seconds)" with lp, \
     "$d/cpu" using 2 title "sieving time (seconds)" with lp, \
     "$d/cpu" using 3 title "cofactorization time (seconds)" with lp
EOF

gnuplot << EOF
set terminal gif
set output '$d/rep.gif'
plot "$d/rep" using 1 title "relations found" with lp
EOF

gnuplot << EOF
set terminal gif
set output '$d/mem.gif'
plot "$d/mem" using 1 title "memory used (MB)" with lp
EOF
