rootsieve: rootsieve.c
	gcc -std=c99 -I.. -DUSE_F2 -O2 -g rootsieve.c -o rootsieve ../build/f2/ffspol.o ../build/f2/fqpol.o ../build/f2/polyfactor.o ../build/f2/libfppol-f2.a /users/caramel/logiciels/gf2x-1.0/confit/lib/libgf2x.a
