#!/bin/sh

hooks() {
    for hook in "$@" ; do
	if ! "`dirname $0`"/post-receive.$hook "$@" > /dev/null 2>&1 ; then
	    echo "$hook failed !" >&2
	    exit 1
	fi
    done
}

hooks ci < /dev/null
hooks email
