#include "cado.h"
#include "mod_mpz_default.h"

#define ecm ecm_mpz
#define ell_pointorder ell_pointorder_mpz
#define ellM_curveorder_jacobi ellM_curveorder_jacobi_mpz
#define ell_curveorder ell_curveorder_mpz

/* The next ones are static so there's no need to rename them, but it's 
   nice to have these functions distinguishable e.g. in profiler output */

#define ecm_stage2 ecm_stage2_mpz

#define ec_arith ec_arith_mpz
#define ec_point_init ec_point_init_mpz
#define ec_point_clear ec_point_clear_mpz
#define ec_point_set ec_point_set_mpz
#define ec_point_swap ec_point_swap_mpz
#define ec_point_print ec_point_print_mpz

#define edwards_neg edwards_neg_mpz
#define edwards_add edwards_add_mpz
#define edwards_sub edwards_sub_mpz
#define edwards_dbl edwards_dbl_mpz
#define edwards_tpl edwards_tpl_mpz
#define edwards_smul_ui edwards_smul_ui_mpz

#define montgomery_A_from_b montgomery_A_from_b_mpz
#define montgomery_dbl montgomery_dbl_mpz
#define montgomery_dadd montgomery_dadd_mpz
#define montgomery_smul_ui montgomery_smul_ui_mpz
#define bytecode_prac_interpret_ec_montgomery bytecode_prac_interpret_ec_montgomery_mpz

#define weierstrass_aff_add weierstrass_aff_add_mpz
#define weierstrass_aff_dbl weierstrass_aff_dbl_mpz
#define weierstrass_aff_from_montgomery weierstrass_aff_from_montgomery_mpz
#define weierstrass_aff_smul_ui weierstrass_aff_smul_ui_mpz
#define weierstrass_proj_add weierstrass_proj_add_mpz
#define weierstrass_proj_dbl weierstrass_proj_dbl_mpz
#define weierstrass_proj_smul_ui weierstrass_proj_smul_ui_mpz

#define ec_parameter_is_valid ec_parameter_is_valid_mpz
#define ec_parameterization_Brent_Suyama ec_parameterization_Brent_Suyama_mpz
#define ec_parameterization_Brent_Suyama_is_valid ec_parameterization_Brent_Suyama_is_valid_mpz
#define ec_parameterization_Montgomery12 ec_parameterization_Montgomery12_mpz
#define ec_parameterization_Montgomery12_is_valid ec_parameterization_Montgomery12_is_valid_mpz
#define ec_parameterization_Montgomery16 ec_parameterization_Montgomery16_mpz
#define ec_parameterization_Montgomery16_is_valid ec_parameterization_Montgomery16_is_valid_mpz
#define ec_parameterization_Z6 ec_parameterization_Z6_mpz
#define ec_parameterization_Z6_is_valid ec_parameterization_Z6_is_valid_mpz

#include "ecm.c"
