#include "cado.h"
#include "modredc_2ul2_default.h"

#define ecm ecm_2ul2
#define ell_pointorder ell_pointorder_2ul2
#define ellM_curveorder_jacobi ellM_curveorder_jacobi_2ul2
#define ell_curveorder ell_curveorder_2ul2

/* The next ones are static so there's no need to rename them, but it's 
   nice to have these functions distinguishable e.g. in profiler output */

#define ecmE_stage2 ecmE_stage2_2ul2

#define ec_arith ec_arith_2ul2
#define ec_point_init ec_point_init_2ul2
#define ec_point_clear ec_point_clear_2ul2
#define ec_point_set ec_point_set_2ul2
#define ec_point_swap ec_point_swap_2ul2
#define ec_point_print ec_point_print_2ul2

#define edwards_neg edwards_neg_2ul2
#define edwards_addsub edwards_addsub_2ul2
#define edwards_add edwards_add_2ul2
#define edwards_sub edwards_sub_2ul2
#define edwards_dbl edwards_dbl_2ul2
#define edwards_tpl edwards_tpl_2ul2
#define edwards_smul_ui edwards_smul_ui_2ul2

#define montgomery_A_from_b montgomery_A_from_b_2ul2
#define montgomery_dbl montgomery_dbl_2ul2
#define montgomery_dadd montgomery_dadd_2ul2
#define montgomery_smul_ui montgomery_smul_ui_2ul2
#define bytecode_prac_interpret_ec_montgomery bytecode_prac_interpret_ec_montgomery_2ul2

#define weierstrass_aff_add weierstrass_aff_add_2ul2
#define weierstrass_aff_dbl weierstrass_aff_dbl_2ul2
#define weierstrass_aff_from_montgomery weierstrass_aff_from_montgomery_2ul2
#define weierstrass_aff_smul_ui weierstrass_aff_smul_ui_2ul2
#define weierstrass_proj_add weierstrass_proj_add_2ul2
#define weierstrass_proj_dbl weierstrass_proj_dbl_2ul2
#define weierstrass_proj_smul_ui weierstrass_proj_smul_ui_2ul2

#define ec_parameter_is_valid ec_parameter_is_valid_2ul2
#define ec_parameterization_Brent_Suyama ec_parameterization_Brent_Suyama_2ul2
#define ec_parameterization_Brent_Suyama_is_valid ec_parameterization_Brent_Suyama_is_valid_2ul2
#define ec_parameterization_Montgomery12 ec_parameterization_Montgomery12_2ul2
#define ec_parameterization_Montgomery12_is_valid ec_parameterization_Montgomery12_is_valid_2ul2
#define ec_parameterization_Montgomery16 ec_parameterization_Montgomery16_2ul2
#define ec_parameterization_Montgomery16_is_valid ec_parameterization_Montgomery16_is_valid_2ul2
#define ec_parameterization_Z6 ec_parameterization_Z6_2ul2
#define ec_parameterization_Z6_is_valid ec_parameterization_Z6_is_valid_2ul2

#include "ecm.c"
