#include "cado.h"
#include "modredc_15ul_default.h"

#define ecm ecm_15ul
#define ell_pointorder ell_pointorder_15ul
#define ellM_curveorder_jacobi ellM_curveorder_jacobi_15ul
#define ell_curveorder ell_curveorder_15ul

/* The next ones are static so there's no need to rename them, but it's 
   nice to have these functions distinguishable e.g. in profiler output */

#define ecm_stage2 ecm_stage2_15ul

#define ec_arith ec_arith_15ul
#define ec_point_init ec_point_init_15ul
#define ec_point_clear ec_point_clear_15ul
#define ec_point_set ec_point_set_15ul
#define ec_point_swap ec_point_swap_15ul
#define ec_point_print ec_point_print_15ul

#define edwards_neg edwards_neg_15ul
#define edwards_addsub edwards_addsub_15ul
#define edwards_add edwards_add_15ul
#define edwards_sub edwards_sub_15ul
#define edwards_dbl edwards_dbl_15ul
#define edwards_tpl edwards_tpl_15ul
#define edwards_smul_ui edwards_smul_ui_15ul

#define montgomery_A_from_b montgomery_A_from_b_15ul
#define montgomery_dbl montgomery_dbl_15ul
#define montgomery_dadd montgomery_dadd_15ul
#define montgomery_smul_ui montgomery_smul_ui_15ul
#define bytecode_prac_interpret_ec_montgomery bytecode_prac_interpret_ec_montgomery_15ul

#define weierstrass_aff_add weierstrass_aff_add_15ul
#define weierstrass_aff_dbl weierstrass_aff_dbl_15ul
#define weierstrass_aff_from_montgomery weierstrass_aff_from_montgomery_15ul
#define weierstrass_aff_smul_ui weierstrass_aff_smul_ui_15ul
#define weierstrass_proj_add weierstrass_proj_add_15ul
#define weierstrass_proj_dbl weierstrass_proj_dbl_15ul
#define weierstrass_proj_smul_ui weierstrass_proj_smul_ui_15ul

#define ec_parameter_is_valid ec_parameter_is_valid_15ul
#define ec_parameterization_Brent_Suyama ec_parameterization_Brent_Suyama_15ul
#define ec_parameterization_Brent_Suyama_is_valid ec_parameterization_Brent_Suyama_is_valid_15ul
#define ec_parameterization_Montgomery12 ec_parameterization_Montgomery12_15ul
#define ec_parameterization_Montgomery12_is_valid ec_parameterization_Montgomery12_is_valid_15ul
#define ec_parameterization_Montgomery16 ec_parameterization_Montgomery16_15ul
#define ec_parameterization_Montgomery16_is_valid ec_parameterization_Montgomery16_is_valid_15ul
#define ec_parameterization_Z6 ec_parameterization_Z6_15ul
#define ec_parameterization_Z6_is_valid ec_parameterization_Z6_is_valid_15ul

#include "ecm.c"
